//! DCRM - Dirmacs CRM
//! A minimal, efficient customer relationship manager
//! Built with Rust + Dioxus + Tailwind CSS

#![allow(non_snake_case)]

use dioxus::prelude::*;

const TAILWIND_CSS: Asset = asset!("/assets/tailwind.css");

mod components;
mod models;
mod pages;
mod state;

use components::{ModalContainer, Sidebar, TopBar};
use models::load_data;
use pages::{ActivitiesPage, ContactsPage, DashboardPage, DealsPage};
use state::{Modal, View};

fn main() {
    dioxus::launch(App);
}

#[component]
fn App() -> Element {
    // Load persisted data or sample data
    let app_data = use_signal(|| load_data());

    // App state
    let current_view = use_signal(|| View::Dashboard);
    let modal = use_signal(|| Modal::None);
    let search_query = use_signal(String::new);

    // Provide context
    use_context_provider(|| app_data);
    use_context_provider(|| current_view);
    use_context_provider(|| modal);
    use_context_provider(|| search_query);

    rsx! {
        // Tailwind v4 CSS (auto-generated by DX from tailwind.css)
        document::Stylesheet { href: TAILWIND_CSS }

        div {
            class: "flex h-screen w-screen overflow-hidden bg-dark-900 text-zinc-100 font-sans antialiased",

            // Sidebar Navigation
            Sidebar {}

            // Main Content Area
            div { class: "flex-1 flex flex-col overflow-hidden",
                // Top Bar with Search
                TopBar {}

                // Page Content
                match *current_view.read() {
                    View::Dashboard => rsx! { DashboardPage {} },
                    View::Contacts => rsx! { ContactsPage {} },
                    View::Deals => rsx! { DealsPage {} },
                    View::Activities => rsx! { ActivitiesPage {} },
                }
            }

            // Modal Container
            ModalContainer {}
        }
    }
}
